---
title: "About"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Bio

I am a postdoctoral fellow at the [Statistical Department of the University of Toronto](https://www.statistics.utoronto.ca/), conducting research in the [Bayesian Demography Lab](https://www.monicaalexander.com/lab/) under the supervision of [Monica Alexander](https://www.monicaalexander.com/about/). My current research focus on racial/ethnic disparity in the experience of parental loss in the US. 

I was a PhD student at [UCLouvain](https://uclouvain.be/fr/index.html) (Belgium), in the Center for Demographic Research [(DEMO)](https://uclouvain.be/en/research-institutes/iacchos/demo) under the supervision of [Bruno Masquelier](https://scholar.google.com/citations?user=OHF3hUYAAAAJ&hl=en). My thesis focused on mortality estimation at the subnational level using Bayesian methods. I am interested in statistics, applied mathematics, R, data visualization, open science and science of science. 

Outside of work, I am a full time dad.


# Experience

Before starting my PhD, I worked at the [Centre for Research on the Epidemiology of Disasters](https://www.cred.be/) (CRED) where I conducted statistical analyses on different research projects: evaluating health profiles and health needs of non-EU migrants arriving in Greece with Médecins du Monde data; assessing the impact of the 2015 Earthquake on hospital admissions in Kathmandu (Nepal) using Tribhuvan University Teaching Hospital data; estimating the civilian mortality during the Syrian conflict focusing on deaths recorded by the Syrian Violation Documentation Center (VDC). I was also involved in supervising master theses, teaching statistics, data manipulation and visualization.


# Education

I did my master in quantitative economics at the [Free University Brussels](https://www.ulb.be/en/ulb-homepage). I trained myself further in statistics by first following an [online micromaster](https://micromasters.mit.edu/ds/) in Statistics and Data Science at the Massachusetts Institute of Technology (MIT) and then, by validating statistics courses at UCLouvain.

I also had the opportunity to follow several workshops (usually 1 week long):

* *[Advances in Mortality Forecasting](https://www.demogr.mpg.de/en/career_6122/international_advanced_studies_in_demography_6682/courses_6931/advances_in_mortality_forecasting_9992/)* by Carlo Giovanni Camarda and Ugofilippo Basellini at the Max Planck Institute for Demographic Research (online) in 2022

* *[Statistical Demography](https://sciencesmaths-paris.fr/f/actualites-fr/cours-raftery)* by Adrian E. Raftery at the Fondation des Sciences Mathématiques de Paris (FSMP) in 2021 

* *Bayesian Spatio-Temporal health Modeling* by Andrew B. Lawson at the Medical University of South Carolina (online) in 2021

* *[Berkeley Formal Demography](https://populationsciences.berkeley.edu/population-center/annual-workshop-on-formal-demography/)* at Berkeley University (online) in 2021

* *[Smoothing Demographic Data](https://www.demogr.mpg.de/en/career_6122/international_advanced_studies_in_demography_6682/courses_6931/smoothing_demographic_data_flexible_models_in_population_studies_7174/)* by Carlo Giovanni Camarda at the Max Planck Institute for Demographic Research (online) in 2020


