---
title: "Introduction to Bayesian Temporal Smoothing"
description: |
  A short introduction to Temporal Smoothing of a proportion with Bayesian statistics. Code in R and STAN presented in the post.
author:
  - name: Benjamin Schlüter
date: 10-08-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

See slides 13, 30-32 from part 2 Wakefield to defines the topics of this post.

Sample prevalence in a area (small- medium size: impact on variation of proportion)

BAYESIAN formula good for smoothing (prior)

```{r, echo=FALSE}
require(tidyverse)
require(scales)
require(viridis)
```



```{r, echo=FALSE}
# Sim decading proportion
exp_decay = function(A, k, t) A*exp(-k*t) + 0.05
t = 0:80
set.seed(1)

df = tibble(
        t = rep(t, 2),
        p = exp_decay(A = 0.2, k = 0.06, t = t)) 
df = df %>% 
        mutate(n = c(rep(100, 81), rep(1000, 81)),
               sim = rbinom(162, n, p),
               p.sim = sim/n)

```

Proportion of individuals with a characteristic over time.

```{r, echo=FALSE}
df %>% 
        mutate(n = factor(n,
                          levels = c(100, 1000),
                          labels = c("n = 100", "n = 1000"))) %>% 
        ggplot(aes(x = t, y = p)) +
        geom_line(aes(col = "true proportion"),
                  linetype = "dashed") +
        geom_point(aes(x = t, y = p.sim, col = "random realizations")) +
        theme_bw() +
        theme(legend.position = c(0.35, 0.79),
              legend.title = element_blank()) +
        scale_color_manual(values = c("true proportion" = "#287D8EFF",
                                      "random realizations" = "#FCA007FF")) +
        labs(y = "Proportion", 
             x = "Time") +
        facet_wrap( ~ n)
```

